### PR TITLE
Modernize the repo a bit

### PR DESCRIPTION
**Pull request by nikolaik**
- Fix markdown deprecation warnings
- Use pathlib instead of os module
- Use subprocess.run
- Format with black
- Add basic test
- Run tests on CI
- Update classifiers

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
Thanks, this looks great 😍

**Comment by johanneswuerbach** [comment]
Confirmed the tests to be working on github actions https://github.com/johanneswuerbach/markdown-inline-mermaid/pull/2 🎉

**Comment by johanneswuerbach** [comment]
Released as `1.0.3` 🚀

**Comment by nikolaik** [comment]
Nice, thanks for the quick review and release @johanneswuerbach !

**Pull request merged**
